name: phoosar
description: "A dating app"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bounceable: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  supabase_flutter: ^1.1.0
  timeago: ^3.6.1
  flutter_facebook_auth: ^7.0.1
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.1
  sized_context: ^1.0.0+4
  pin_code_fields: ^8.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  riverpod_test: ^0.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
