name: phoosar
description: "A dating app"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.8+19

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  
  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bounceable: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  url_strategy: ^0.3.0
  supabase_flutter: ^2.6.0
  timeago: ^3.6.1
  flutter_facebook_auth: ^7.1.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.1
  sized_context: ^1.0.0+4
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.1
  firebase_analytics: ^11.2.0
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  intl_phone_number_input: ^0.7.4
  step_progress_indicator: ^1.0.2
  gif_view: ^0.4.4
  video_player: ^2.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  riverpod_test: ^0.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - shorebird.yaml
