// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSni1VyCXVd-JuNpq9VMS0Byqy-6GKpnw',
    appId: '1:98376363970:web:5e72e7175228f64197f05b',
    messagingSenderId: '98376363970',
    projectId: 'newsdev-7afbf',
    authDomain: 'newsdev-7afbf.firebaseapp.com',
    storageBucket: 'newsdev-7afbf.appspot.com',
    measurementId: 'G-3WHSTK9YEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm-Gdrmqi9_DdX4YiC6FMTSgZ1p9bhDn4',
    appId: '1:98376363970:android:ed15c25ff9d0b40f97f05b',
    messagingSenderId: '98376363970',
    projectId: 'newsdev-7afbf',
    storageBucket: 'newsdev-7afbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yLgf1Wb_QauxC3jn7KITTjXbJoo8cuQ',
    appId: '1:98376363970:ios:c6a8124003eaa7f697f05b',
    messagingSenderId: '98376363970',
    projectId: 'newsdev-7afbf',
    storageBucket: 'newsdev-7afbf.appspot.com',
    iosClientId: '98376363970-rhbkts7ddqbi09g9n2hp29v2n7bd8q8h.apps.googleusercontent.com',
    iosBundleId: 'com.moc.phoosar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yLgf1Wb_QauxC3jn7KITTjXbJoo8cuQ',
    appId: '1:98376363970:ios:71e21902d989728d97f05b',
    messagingSenderId: '98376363970',
    projectId: 'newsdev-7afbf',
    storageBucket: 'newsdev-7afbf.appspot.com',
    iosClientId: '98376363970-ocr9h4gjg8ku7tss2o34ckah601rmrb2.apps.googleusercontent.com',
    iosBundleId: 'com.moc.phoosar.RunnerTests',
  );
}
