// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxd1jA0dOo3MVNmrN36f756Aj8ukWEsE',
    appId: '1:386971559769:web:0c59ab7c0a1ad24a344e48',
    messagingSenderId: '386971559769',
    projectId: 'phoo-sar',
    authDomain: 'phoo-sar.firebaseapp.com',
    storageBucket: 'phoo-sar.appspot.com',
    measurementId: 'G-68XD8X4HZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyH5MLyZWaaFBnMMxA8V8XDR0zIIFoo0',
    appId: '1:386971559769:android:51e542450bc94ce1344e48',
    messagingSenderId: '386971559769',
    projectId: 'phoo-sar',
    storageBucket: 'phoo-sar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvBFP32svo3Sn_tuOhV3_jutB0FnMRFv4',
    appId: '1:386971559769:ios:5fbc19bbdd467ae0344e48',
    messagingSenderId: '386971559769',
    projectId: 'phoo-sar',
    storageBucket: 'phoo-sar.appspot.com',
    iosBundleId: 'com.moc.phoo-sar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvBFP32svo3Sn_tuOhV3_jutB0FnMRFv4',
    appId: '1:386971559769:ios:2cbcdabaf90b5d76344e48',
    messagingSenderId: '386971559769',
    projectId: 'phoo-sar',
    storageBucket: 'phoo-sar.appspot.com',
    iosBundleId: 'com.moc.phoosar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoxd1jA0dOo3MVNmrN36f756Aj8ukWEsE',
    appId: '1:386971559769:web:fdc431d22e711bd0344e48',
    messagingSenderId: '386971559769',
    projectId: 'phoo-sar',
    authDomain: 'phoo-sar.firebaseapp.com',
    storageBucket: 'phoo-sar.appspot.com',
    measurementId: 'G-85819QG86N',
  );

}